### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by rlechetaudemy** [urbanairship/airship-flutter#1]
Hi, what's the plan to support Push Notifications for Flutter?

**Comment by rlepinski** [comment]
Push notifications are working. We only are exposing a push received event so far, not a push opened.

**Comment by rlepinski** [comment]
What events are you looking for?

**Comment by viniciusfragelli** [comment]
Hi, I work with Ricardo Lecheta, and we have an Flutter project that will use the Libs. There's any estimate date to the conclusion? We're kind in a hurry.
Best regards!

**Comment by rlepinski** [comment]
Push notifications are currently working in the plug-in. What events do you need exposed?

**Comment by rlepinski** [comment]
@viniciusfragelli @rlechetaudemy I just pushed a change to expose all push events on Android (push received and notification response) as well as deep link events.

**Comment by viniciusfragelli** [comment]
Notifications and Push events

**Comment by rlepinski** [comment]
@viniciusfragelli I cant promise any timeline for an official release, but the current state of the plugin supports notifications and message center on both iOS and Android. If you find any issues please let me know.
