### ISSUE TITLE
app crashed in ios when push received

### ISSUE THREAD

**Issue by huhuan-yj** [urbanairship/airship-flutter#102]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

airship_flutter 5.0.1 

### What are the versions of any relevant development tools you are using?

[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale
zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.57.0)
[✓] Connected device (3 available)
# Report

### What unexpected behavior are you seeing?

click the notification and open app ,then crashed, it only happened on iphone
### What is the expected behavior?

click the notification and open app, app can open successful
### What are the steps to reproduce the unexpected behavior?

just send a push message with deeplink, and click the message when push received
### Do you have logging for the issue?

I see the log, and found that "type 'Null' is not a subtype of type 'String'" error in class airship_flutter.dart line 60. It reference the notificationId cannot be null. Then I went to the airship docs,found notificationId only used in Android. But I don't known if it was the real cause. 
![image](https://user-images.githubusercontent.com/84067160/142989259-c9fc214f-8085-42a1-a057-980fe7ffcc0b.png)
![image](https://user-images.githubusercontent.com/84067160/142989301-98af90ab-0ad6-4274-863c-0e97f90d2468.png)

**Comment by rlepinski** [comment]
Thanks for the report, we will look into this

**Comment by Ulrico972** [comment]
Hello, we released today a version of our flutter framework that should fix your issue.
I'm closing this issue, feel free to reopen it if it's not resolved.

**Comment by huhuan-yj** [comment]
> Hello, we released today a version of our flutter framework that should fix your issue. I'm closing this issue, feel free to reopen it if it's not resolved.

Thanks a lot , after upgrade the new version, it resolved
