### ISSUE TITLE
iOS app crash on start. "unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by andrewescutia** [urbanairship/airship-flutter#107]
# Preliminary Info

### What Airship dependencies are you using?

pubspec.yaml:
airship_flutter: ^5.1.0

Podfile.lock:
PODS:
  - Airship/Automation (16.1.2):
    - Airship/Core
  - Airship/Basement (16.1.2)
  - Airship/Core (16.1.2):
    - Airship/Basement
  - Airship/MessageCenter (16.1.2):
    - Airship/Core
  - Airship/PreferenceCenter (16.1.2):
    - Airship/Core
  - airship_flutter (5.1.0):
    - Airship/Automation (~> 16.1.1)
    - Airship/Core (~> 16.1.1)
    - Airship/MessageCenter (~> 16.1.1)
    - Airship/PreferenceCenter (~> 16.1.1)
    - Flutter

### What are the versions of any relevant development tools you are using?
[✓] Flutter (Channel stable, 2.8.0, on macOS 11.6 20G165 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.63.2)

# Report

### What unexpected behavior are you seeing?
ios app crash on startup

### What are the steps to reproduce the unexpected behavior?
This doesnt appear to occur on   airship_flutter: ^4.4.0

Create a new flutter app. 
add dependency for airship_flutter. 
adjust the ios platform to 12.0 in both locations per airship docs.
add an appropriate airshipconfig.plist file
run to see the crash.

I also attempted to add the ObjC linker flag per this post:
https://stackoverflow.com/questions/18897103/urban-airship-crashes-when-calling-takeoff

### Do you have logging for the issue?
iOS console output log:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString count]: unrecognized selector sent to instance 0xe629e2c297789435'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000102c99ba4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010231bbe7 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000102ca8811 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   CoreFoundation                      0x0000000102c9e0ac ___forwarding___ + 1433
	4   CoreFoundation                      0x0000000102ca01d8 _CF_forwarding_prep_0 + 120
	5   libswiftFoundation.dylib            0x0000000103da20c1 $ss15_arrayForceCastySayq_GSayxGr0_lFSayyXlGAByXlRszr0_lIetgo_Tp5 + 673
	6   libswiftFoundation.dylib            0x0000000103dcf68f $sSa10FoundationE36_unconditionallyBridgeFromObjectiveCySayxGSo7NSArrayCSgFZ + 239
	7   AirshipKit                          0x000000010121b3bc $s10Ai<…>

**Comment by rlepinski** [comment]
Thanks for the report, we will take a look

**Comment by oristanovic** [comment]
@andrewescutia Not sure if it's related but the version in your podfile should be 16.1.1 not 16.1.2. Could you attach a very basic sample app that reproduces the crash (it's not reproducible on my side)?

**Comment by andrewescutia** [comment]
Sorry for the delay. This appeared to be an error on my end within the AirshipConfig.plist file.

I had

    <key>urlAllowListScopeOpenUrl</key>
    <string>*</string>

but it should have been

    <key>urlAllowListScopeOpenUrl</key>
    <array>
      <string>*</string>
    </array>
