### ISSUE TITLE
Remove jCenter

### ISSUE THREAD

**Issue by ueman** [urbanairship/airship-flutter#112]
# Preliminary Info

### What Airship dependencies are you using?
`airship_flutter: 5.1.0`

# Report

### What unexpected behavior are you seeing?
jCenter is still listed as a source in the build.gradle

### What is the expected behavior?
[jCenter gets removed because it shuts down on February 1, 2022.](https://blog.gradle.org/jcenter-shutdown) It should be replaced with `mavenCentral()`.

### What are the steps to reproduce the unexpected behavior?
Look at these lines: https://github.com/urbanairship/airship-flutter/blob/main/android/build.gradle#L9-L25

### Do you have logging for the issue?
No

**Comment by Ulrico972** [comment]
Hello, thanks for the report. We'll change that in the next version
