### ISSUE TITLE
Method setNamedUser has no effect in AirshipConsole

### ISSUE THREAD

**Issue by vlkonoshenko** [urbanairship/airship-flutter#113]
# Preliminary Info

### What Airship dependencies are you using?
<img width="382" alt="Screenshot 2022-01-24 at 16 09 27" src="https://user-images.githubusercontent.com/15077780/150788581-377b11ca-550f-47e5-bcd6-09245e5c42ef.png">

### What are the versions of any relevant development tools you are using?
Flutter 2.8.0 • channel stable 

# Report

### What unexpected behavior are you seeing?
When calling setNamedUser I want to find the user id in the airship console

`await Airship.setNamedUser('user-id-test');`
<img width="714" alt="Screenshot 2022-01-24 at 15 58 03" src="https://user-images.githubusercontent.com/15077780/150786937-bac5d5ac-4f12-40e4-8fe2-32ed081e620a.png">

### What is the expected behavior?
<img width="714" alt="Screenshot 2022-01-24 at 15 58 33" src="https://user-images.githubusercontent.com/15077780/150787007-6cc03dfc-fd4c-400a-a2f3-8df94d6760c6.png">

### What are the steps to reproduce the unexpected behavior?
Install app -> call set name-> try send named notification

### Do you have logging for the issue?
No

**Comment by vlkonoshenko** [comment]
How to manage 2 accounts in one device if the channel ID is the same? I can`t set up a user name.

**Comment by rlepinski** [comment]
@vlkonoshenko do you have any device logs you can share? Chat platform are you having issues on?

**Comment by vlkonoshenko** [comment]
> @vlkonoshenko do you have any device logs you can share? Chat platform are you having issues on?

I do not have log. Method called without error, but in airship console I can't found this user name. I can record video or we can get call and I display process

**Comment by rlepinski** [comment]
I meant `which` platform. Is this happening on iOS or Android?

**Comment by vlkonoshenko** [comment]
> I meant `which` platform. Is this happening on iOS or Android?

Android

**Comment by rlepinski** [comment]
Going to close due to inactivity.
