### ISSUE TITLE
Named User cannot be unset in IOS

### ISSUE THREAD

**Issue by arashgm** [urbanairship/airship-flutter#120]
# Preliminary Info

### What Airship dependencies are you using?

5.1.1

# Report

### What unexpected behavior are you seeing?

Named User cannot be unset in IOS, on Previous versions with  `await Airship.setNamedUser('');` on logout we could remove the namedUser. on Android the same call can clear the namedUser fine and calling `await Airship.namedUser` will return null but on IOS it returns the last namedUser.   

### What is the expected behavior?

there should be a way to unset the namedUser in IOS. based on the documentation it is possible by `Airship.contact.reset()` but in the plugin there is no method to do so

workaround : if you look at the SwiftAirshipPlugin.swift 
https://github.com/urbanairship/airship-flutter/blob/ba687f04934ac06685c6ed9e8f342f46912b3c1e/ios/Classes/SwiftAirshipPlugin.swift#L362

you are checking the arguments type and if its not String the else block which will reset the namedUser will be called, so passing a null dynamic argument (cause the parameter is non nullable) solve the issue but i think it can be easily fix if you expose a method to reset the namedUsers if the user do logging out.

**Comment by rlepinski** [comment]
Right, so the flutter api should make the named user optional but its not marked that way https://github.com/urbanairship/airship-flutter/blob/main/lib/src/airship_flutter.dart#L226

We will make it optional as well as properly handle an empty named user ID. Thanks for the ticket!

**Comment by arashgm** [comment]
great thanks

**Comment by rlepinski** [comment]
Fixed in 5.3.0
