### ISSUE TITLE
InboxMessageView - Web Deep Links not working

### ISSUE THREAD

**Issue by JackRKelly** [urbanairship/airship-flutter#125]
# Preliminary Info

### What Airship dependencies are you using?

airship_flutter - 5.2.0

### What are the versions of any relevant development tools you are using?

- Visual Studio Code, running with Debugger using official Dart and Flutter extensions
- I should note, when creating message in Airship, we are not using the "Deep Link" feature, we are simply assigning URLs to buttons. So the `uairship://` scheme is not appended to these links.

Flutter Doctor:
```
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.1 21C52 darwin-arm, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.66.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability
```

# Report

### What unexpected behavior are you seeing?

When using the `InboxMessageView` widget provided by `airship_flutter`, web deep links (Example deep link: https://amc.film/3C3S1d1) are not internally routing to the respective screen in-app and are opening in-browser. Though when opened outside of the application, the deep links route to the correct screen in-app.

### What is the expected behavior?

When clicking on a URL/Deep Link embedded in the `InboxMessageView` widget provided by `airship_flutter`, the user should be routed to the correct screen in-app.

### What are the steps to reproduce the unexpected behavior?

1. Open the application.
2. Navigate to an Airship message (Rendered by `InboxMessageView`).
3. Click on an deep link embedded in the `InboxMessageView`.
4. Notice: The user is redirected to their respective link in their browser. 
     Expected: The user should be routed to the respective screen in-app. (Again, when opening the same link from outside of the app, the user is redirected to the correct screen in-app as expected.)

### Do you have logging for the issue?

No pertinent logs exist as no errors were thrown from this behavior.

# Other Notes

When utilizing the WebView widget in-app from the `webview_flutter` package, we have access to a [navigationDelegate](https://pub.dev/documentation/webview_flutter/latest/webview_flutter/NavigationDelegate.html) argument where we can decide how to handle a specific navigation request and determine if a URI matches our deep link scheme. Is the expectation that developers should implement Airship messages in a WebView to have deep link support? Should there be a navigationDelegate or similar argument on `InboxMessageView`? Or should this behavior work out of the box?

**Comment by rlepinski** [comment]
We have two actions that handle URLs - deep link and open external url action. Open external urls are assumed to be external while deep links are internal. Do you know which one is being used? If you can provide the message HTML I could see what action is being ran.

**Comment by JackRKelly** [comment]
We are using the open external link.

```html
<a href="uairship://run-actions?open_external_url_action=%22http%3A%2F%2Famc.film%2F2pIvfo9%22">
    <span>Click Here</span>
</a>
```

But it seems the OS refuses to reopen the app it came from after following that link. Which again, is why we handle the navigation events in the WebView widget and explicitly search URIs for our deep link scheme. 

When trying to use a "Deep Link" as opposed to a "Web Page"/external link. The button isn't clickable, I have tested this on a physical device and simulator. See the HTML for the deep link button below:

```html
<a href="uairship://run-actions?deep_link_action=%22http%3A%2F%2Famc.film%2F2pIvfo9%22">
    <span>Click Here</span>
</a>
```

**Comment by rlepinski** [comment]
I am not sure why it would not be clickable? It looks the same to me. Could you remote debug the webview to see whats causing it to not be clickable? 

The quickest path would be to resolve this instead of coming up with a different solution.

**Comment by JackRKelly** [comment]
I believe that was just a local issue on my end.

For our previous application, we updated a predicate for `open_external_url_action` (See "Setting a predicate" here: https://docs.airship.com/platform/ios/actions/). 

The code looked like:
```
UAirship.Shared.ActionRegistry.UpdatePredicate(predicate, "open_external_url_action");
```

But in the documentation for the flutter SDK, there is no actions page, as I assume it has not been implemented.

And the uairship run action deep link isn't working (it _is_ clickable, but doesn't navigate as expected). So we are expecting a way to handle `open_external_url_action`.

**Comment by rlepinski** [comment]
The deep link action, assuming we can get that to work, should do what you want to do here. You can use it for everything and the URLs you want to open externally you can from the deep link handler. How are you implementing the deep link listener?

**Comment by JackRKelly** [comment]
We have implemented the deep link handler with the follow snippets below (with some non-critical logic removed):

```dart
class DeepLinkService {
  final GetNavigationService _get;
  final BitlyService _bitlyService;
  final AnalyticsService _analyticsService;

  final _appLinkStreamController = StreamController<AppLink?>.broadcast();
  Stream<AppLink?> getAppLinkStream() => _appLinkStreamController.stream;

  late StreamSubscription<Uri?> _stream;

  DeepLinkService(
    this._get,
    this._bitlyService,
    this._analyticsService,
  );

  Future<void> start() async {
    try {
      logger.info('Deep Link Service Started');

      final initialUrl = await getInitialUri();
      onUriReceived(initialUrl);

      _stream = uriLinkStream.listen((uri) {
        onUriReceived(uri);
      });
    } catch (e) {
      logger.error('Error attempting to start DeepLink Service', exception: e);
    }
  }

  Future<void> stop() async {
    return _stream.cancel();
  }

  Future<void> onUriReceived(Uri? uri) async {
    try {
      if (uri != null) {
        logger.info('Deep Link Received ${uri.toString()}');

        if (uri.host != 'amc.film') {
          _appLinkStreamController.sink.add(
            AppLink(uri: uri),
          );

          return;
        }

        final expandedUri = await _bitlyService.expand(uri.toString());

        _analyticsService.reportDeepLink(expandedUri);

        //Authentication guard
        final authedRouteFound = _matchAuthRoute(expandedUri);

        if (authedRouteFound && AuthenticationService.user.isLoggedOut()) {
          var user = await _get.toNamed(LoginPage.route());

          if (user == null) {
            return;
          }
        }

        await _get.routeFromExternalUrl(expandedUri);
      }
    } catch (ex) {
      logger.error('Error receiving deep link', exception: ex);
    }
  }
}
```

We are including it in our providers in our main app file:

```dart
  List<SingleChildWidget> _providers() {
    return [
      ProxyProvider3<GetNavigationService, BitlyService, AnalyticsService, DeepLinkService>(
        update: (_, get, bitly, analyticsService, previous) => previous ?? DeepLinkService(get, bitly, analyticsService),
        dispose: (_, service) => service.stop(),
      ),
      // Other entries hidden
    ];
  }
```

And we are initializing it in the view model of our splash screen:

```dart
  @override
  Future<void> onLoad() async {
    _deepLinkService.start();
  }
```

Hopefully these snippets help paint the picture of our implementation. If you need more context, let me know. Thanks!

**Comment by rlepinski** [comment]
@JackRKelly You need to register for Airship's deep links:

```
Airship.onDeepLink
    .listen((deepLink) {
        Uri uri = Uri.parse(deepLink);
        onUriReceived(uri);
    });
```

**Comment by JackRKelly** [comment]
> @JackRKelly You need to register for Airship's deep links:
> 
> ```
> Airship.onDeepLink
>     .listen((deepLink) {
>         Uri uri = Uri.parse(deepLink);
>         onUriReceived(uri);
>     });
> ```

Awesome! This has fixed it. I was unaware I had to register that listener. May I recommend adding a snippet (to recommend the developer check if they have attached a listener) to the [manage deep links page](https://docs.airship.com/guides/messaging/user-guide/project/config/deep-links/)?

**Comment by rlepinski** [comment]
@JackRKelly I passed on your recommendation to our docs team
