### ISSUE TITLE
Android InboxMessageView CTA link is not opening

### ISSUE THREAD

**Issue by rsp-84** [urbanairship/airship-flutter#126]
# Preliminary Info

### What Airship dependencies are you using?
airship_flutter - 5.1.0

### What are the versions of any relevant development tools you are using?
Visual Studio Code, running with Debugger using official Dart and Flutter extensions

Flutter Doctor: 
```
    [✓] Flutter (Channel stable, 2.10.1, on macOS 11.6.4 20G417 darwin-x64, locale en-US)
    [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.64.2)
    [✓] Connected device (3 available)
    [✓] HTTP Host Availability
```

# Report

### What unexpected behavior are you seeing?
Using the `InboxMessageView` widget provided by `airship_flutter` a call to action link is not opening a browser and navigating to the URL on an Android device. The link is working on iOS.

### What is the expected behavior?
When clicking the link (button) within the inbox message on Android it should open a web browser to navigate to the URL as it does on iOS.

### What are the steps to reproduce the unexpected behavior?
1. Open an inbox message that contains a CTA button link to a URL.
2. Click the button
3. Nothing happens on Android while on iOS a safari browser is opened and navigates to the URL

### Do you have logging for the issue?
```
UALib(  851): Running run actions command with callback for URL: uairship://run-action-cb/^u/%22https%3A%2F%2F[URL]%2F%22/ua-cb-3
UALib(  851): Action: ^u, Args: "https://[URL]/", Callback: ua-cb-3
UALib(  851): Action com.urbanairship.actions.OpenExternalUrlAction@1b47de3 is unable to accept arguments: ActionArguments { situation: 3, value: "https:\/\/[URL]\/", metadata: Bundle[{com.urbanairship.REGISTRY_ACTION_NAME=^u, com.urbanairship.RICH_PUSH_ID_METADATA=UPxD4L9jEeyJ4QJCLOtUNA}] }
UALib(  851): Running run actions command with callback for URL: uairship://run-action-cb/custom_action_cta_click/%7B%22ctaTitle%22%3A%22Gift%20Cards%22%2C%22messageTitle%22%3A%2220220418%20Test%22%2C%22headlineText%22%3A%22Header%20content%22%7D/ua-cb-4
UALib(  851): Action: custom_action_cta_click, Args: {"ctaTitle":"Gift Cards","messageTitle":"20220418 Test","headlineText":"Header content"}, Callback: ua-cb-4
V/InputMethodManager(  851): b/117267690: Failed to get fallback IMM with expected displayId=6 actual IMM#displayId=0 view=com.urbanairship.messagecenter.webkit.MessageWebView{b8298d6 VFEDHVC.. .F...... 0,0-1080,1823}

```

**Comment by rlepinski** [comment]
Are you registering your own action? Could you provide that source?

**Comment by rlepinski** [comment]
https://github.com/urbanairship/android-library-dev/blob/main/urbanairship-core/src/main/java/com/urbanairship/actions/OpenExternalUrlAction.java#L76

Both iOS and Android check for the allow list, so hopefully you have the rule on iOS defined but not on Android. To accept all, add `urlAllowList = *` to your config on Android.

**Comment by rsp-84** [comment]
> https://github.com/urbanairship/android-library-dev/blob/main/urbanairship-core/src/main/java/com/urbanairship/actions/OpenExternalUrlAction.java#L76
> 
> Both iOS and Android check for the allow list, so hopefully you have the rule on iOS defined but not on Android. To accept all, add `urlAllowList = *` to your config on Android.

This solved the issue! It appears I was using `urlAllowListScopeOpenURL = *` 

Thanks for the help!

**Comment by rlepinski** [comment]
That one would of worked too but the casing is wrong `urlAllowListScopeOpenUrl`
