### ISSUE TITLE
Cannot create appbundle on release mode with flutter 3.0.0

### ISSUE THREAD

**Issue by kkoken** [urbanairship/airship-flutter#130]
airship_flutter: `5.2.0`
flutter: `3.0.0` 
dart: `>=2.17.0 <3.0.0`
android sdk: `16.3.0`

After the flutter **3.0.0** release, I tried to create **appBundle** on release mode on the Android side and I could not.

Error:
```
3 warnings
e: /Users/kaantahakoken/.pub-cache/hosted/pub.dartlang.org/airship_flutter-5.2.0/android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt: (50, 1): Class 'InboxMessageViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /Users/kaantahakoken/.pub-cache/hosted/pub.dartlang.org/airship_flutter-5.2.0/android/src/main/kotlin/com/airship/flutter/AirshipPlugin.kt: (51, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':airship_flutter:compileReleaseKotlin'.
> Compilation error. See log for more details
```

Then I update the airship_flutter to the latest,`5.5.0` with android SDK `16.4.0`.
It gave the same error as well.

PS: It works when I was using:
airship_flutter: `5.2.0`
flutter: `2.10.3` 
dart: `>=2.16.0 <3.0.0`
android sdk: `16.3.0`

**Comment by rlepinski** [comment]
@kkoken Created a branch GH-130 that should have those issues resolved if you want to start using flutter 3.0.

It looks like the flutter team added a bunch of nullability annotations that are causing slightly different signatures in kotlin. I might file some flutter issues to see if the "breaking" nullability changes could be reverted since I believe this will cause incompatibility issues with flutter 2

**Comment by rlepinski** [comment]
Looks like someone already filed a similar issue - https://github.com/flutter/flutter/issues/103583

**Comment by kkoken** [comment]
@rlepinski thanks for your help. For now, we are not planning to switch immediately **3.0.0**. We are using a lot of 3rd parties;but, I will give a try. 

Also, I will try to use with **2.10.3** as well and keep you posted.

Thank you for all your afford.

Have a nice day : )

**Comment by kkoken** [comment]
[#103561](https://github.com/flutter/flutter/issues/103561)

**Comment by AmiralBl3ndic** [comment]
Hello, I am working on a new app that uses features that are only provided with Flutter 3, so I cannot downgrade my Flutter version to 2.10.3.
Your example app runs fine on branch GH-130, is there any more features/fix that this branch should bring? Also, is there an ETA on resolving this issue? 

Thanks a lot for your work! 🚀
