### ISSUE TITLE
InboxMessages DateTime is not UTC ISO-8601 format

### ISSUE THREAD

**Issue by PetrasBartusis** [urbanairship/airship-flutter#139]
Calling: 
```dart
await Airship.inboxMessages;
```
gives you a list of message center messages. The `InboxMessage` `sentDate` parameter does not come in `UTC` `ISO-8601` format.

Example InboxMessage:
```
InboxMessage(
  title = "Test message"
  messageId = "9e-9gEn4Ee2BeQJC4LzypA"
  sentDate = "2022-10-12T06:42:38"
  expirationDate = null
  listIcon = null
  isRead = false
  extras = {_InternalLinkedHashMap} size = 0
)
```

# Preliminary Info

### What Airship dependencies are you using?
Airship 6.1.0 https://pub.dev/packages/airship_flutter (latest current version)

# Report

### What unexpected behavior are you seeing?
I expect the dates to come as `UTC` `ISO-8601` so operations like timezone conversion and dateTime comparison could be done

### What is the expected behavior?
I expect the date to come as  "2022-10-12T06:42:38Z" so when `DateTime` parse methods are used, dateTime is set correctly.

### What are the steps to reproduce the unexpected behavior?
Send a message center message, then get that InboxMessage through `await Airship.inboxMessages`.

**Comment by jyaganeh** [comment]
Hi @PetrasBartusis, thanks for raising this issue. I agree that we should be returning these in a format that's easily parsed by `DateTime`. The `sentDate` should be in UTC time already, it's just that the string format is missing the timezone component.

I'll add this to our backlog, but it might take us a little while to get to it. In the meantime, you could use `DateFormat` (from the `intl` package) to parse these timestamps into proper UTC `DateTime` objects, like this:

```dart
import 'package:intl/intl.dart';

// ...

DateFormat dateFormat = DateFormat("yyyy-MM-DDTHH:mm:ss");

String dateString = "2022-10-12T06:42:38";

// Passing `utc = true`, to parse as UTC instead of local time. 
DateTime dateTime = dateFormat.parse(dateString, true);
}

print(dateTime.isUtc); // -> true
print(dateTime); // -> 2022-10-12 06:42:38.000Z
print(dateTime.toIso8601String());  // -> 2022-10-12 06:42:38.000Z
```

**Comment by PetrasBartusis** [comment]
Hi @jyaganeh! Thank you for the quick answer!

Thank you for the tip. This is a better solution rather than the one I currently used to solve this issue. Will include it in my codebase!
