### ISSUE TITLE
The size of the iOS installation package is abnormal

### ISSUE THREAD

**Issue by baoluchuling** [urbanairship/airship-flutter#145]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
airship_flutter: 6.1.0

### What are the versions of any relevant development tools you are using?
Flutter 3.3.4
Xcode 13.4.1

# Report

### What unexpected behavior are you seeing?
The installation size of iOS has increased by about 40m

airship_flutter: 5.4.0   ios-library: 16.7.0      ios framework size：19.3m
**airship_flutter: 6.1.0   ios-library: 16.9.3      ios framework size：61.9m**
airship_flutter: -----   ios-library: 16.10.2    ios framework size：20.4m

### What is the expected behavior?
 ios-library is greater than or equal to 16.10.0

**Comment by rlepinski** [comment]
The 16.9 series also took 4 mins to build. I think the compiler optimization for swift was causing it to blow up in both size and build time. We will get a release out tomorrow with the new SDK.

**Comment by baoluchuling** [comment]
Thanks, I'm looking forward to tomorrow's update.

**Comment by rlepinski** [comment]
6.2.0 is out
