### ISSUE TITLE
Update to Airship iOS 16.10?

### ISSUE THREAD

**Issue by mnespor** [urbanairship/airship-flutter#146]
# Preliminary Info

Can a new version of airship_flutter that depends on Airship iOS @16.10 be released?

### What Airship dependencies are you using?
airship_flutter 6.1.0

### What are the versions of any relevant development tools you are using?
Xcode 14.0.1

# Report

### What unexpected behavior are you seeing?
I can't use the Live Activities features in an app that has a Flutter component.

### What is the expected behavior?
Either of these two behaviors:
- Opportunity to upgrade to a version of `airship_flutter` that automatically installs `Airship/Core` at 16.10 or higher, or
- Successful pod install with `'Airship/Core', '16.10.3'` in `Podfile` and `airship_flutter: ^6.1.0` in `pubspec.yaml`

### What are the steps to reproduce the unexpected behavior?
1. In the sample project, specify `pod 'Airship/Core', '16.10.3'

Thanks!

**Comment by rlepinski** [comment]
I have this branch - https://github.com/urbanairship/airship-flutter/pull/147

For live activities, you need to do a restore call and a track call when you start one. The track call is straightforward, but the restore call not so much since we call takeOff for the plugin. I think the best bet for you is to use this snippet in application:didFinishLaunching

```
 NotificationCenter.default.addObserver(
        forName: Airship.airshipReadyNotification,
        object: nil,
        queue: nil
      ) { _ in
          if #available(iOS 16.1, *) {
              Task {
                  await Airship.channel.restoreLiveActivityTracking {
                      restorer in
                      // update this to match your types
                      await restorer.restore(
                        forType: Activity<DeliveryAttributes>.self
                      )
                  }
              }
          }
      }
```

That will allow you to integrate into AIrship without worrying about where takeOff is called.

**Comment by rlepinski** [comment]
6.2.0 is out with the update

**Comment by mnespor** [comment]
Thanks @rlepinski! My problem was that the (mainly non-Flutter) project contained a single Flutter view, locking us into 16.9. I don't have any particular concerns about the live activity API yet.
