### ISSUE TITLE
Airship.onChannelRegistration is never called on iOS

### ISSUE THREAD

**Issue by andrewescutia** [urbanairship/airship-flutter#152]
### What Airship dependencies are you using?
airship_flutter: ^6.2.1

### What are the versions of any relevant development tools you are using?
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.74.2)
[✓] Connected device (3 availabl
# Report

### What unexpected behavior are you seeing?
Airship.onChannelRegistration is never called on iOS. I believe the discrepancy is within `AirshipEventHandler.swift`. It appears that file no longer abides by the `RegistrationDelegate` therefore the function is never executed. I believe the current signature for the `RegistrationDelegate` within the iOS library looks like this.
  ` @objc optional func apnsRegistrationSucceeded(withDeviceToken deviceToken: Data)`.

I think this may have been an issue since version 5.0 of the library when the reference to the `RegistrationDelegate` was updated.

The file in question: https://github.com/urbanairship/airship-flutter/blob/main/ios/Classes/AirshipEventHandler.swift

**Comment by oristanovic** [comment]
@andrewescutia Thanks for the report, we're looking into it.

**Comment by rlepinski** [comment]
Should be fixed in 6.2.2
