### ISSUE TITLE
iOS Notification Options support

### ISSUE THREAD

**Issue by jan-koz** [urbanairship/airship-flutter#154]
Please add support of iOS Notifications Options to make Airship Flutter package more reliable and highly customisable.

**Comment by rlepinski** [comment]
Working on a major SDK update where I will add this with foreground presentation options.

**Comment by rlepinski** [comment]
@tomalabaster You may need to delay setting the options til the next run loop by wrapping what you have in
```
DispatchQueue.main.async {

}
```

We have a major plugin rewrite coming that will add support for this and potentially be able to set it per notification all through flutter.  This PR is the start of it - https://github.com/urbanairship/airship-flutter/pull/161 we are just wrapping up a major native SDK release then we will focus on getting plugins up to date.  I am hoping for a new flutter plugin by the end of this month.

**Comment by tomalabaster** [comment]
Thanks @rlepinski will give that a try and keep an eye out :+1:
