### ISSUE TITLE
iOS production key

### ISSUE THREAD

**Issue by jan-koz** [urbanairship/airship-flutter#167]
Hi,
In the documentation it is stated that for Android airshipconfig.properties file I can set the isProduction flag and this is how production key and secret will be used. What is the rule for iOS AirshipConfig.plist file. How is it determined which key and secret is used?

**Comment by khmMouna** [comment]
`isProduction` exists for both iOS and Android. Setting this property on `AirshipConfig.plist` file for iOS will let the SDK determine which key should use.

**Comment by jan-koz** [comment]
Is development key and secret used when the key is not set at all?
