### ISSUE TITLE
Airship setUserNotificationsEnabled malfunction on Android

### ISSUE THREAD

**Issue by AnastasiiaSob** [urbanairship/airship-flutter#173]
# Preliminary Info

### What Airship dependencies are you using?
airship_flutter: ^6.3.2

### What are the versions of any relevant development tools you are using?
Physical Android device Galaxy S21 , Android v. 13
Flutter 3.10.5

# Report

### What unexpected behavior are you seeing?
I am using Airship in Flutter for my iOS and Android Apps. According to [Airship Documentation for Flutter](https://docs.airship.com/platform/mobile/push/getting-started/?groupid=flutter) setting Airship.setUserNotificationsEnabled(true) should show a prompt so user can decide if they want push notifications or not. It happens both on iOS and on Android. The difference is that Android always sets it to 'true', event if the user chose 'Dont`t allow push notifications'.

### What is the expected behavior?
If a user choose 'Don`t allow notifications', the callback variable should be 'false' on Android.

### What are the steps to reproduce the unexpected behavior?
```
Airship.setUserNotificationsEnabled(true).then((status) => {

 // status here is always 'true' on Android
 // if I open App settings, it is correctly false
 // but I need to implement some features that relying on the status variable
 // in iOS, the status is always correct, so it can be 'true' or 'false' according to users choice

}
```
### Do you have logging for the issue?
No

**Comment by rlepinski** [comment]
Thats a local flag on the push manager that you can override at anytime, it does not reflect the status of notifications. You can use this method on 7.0.0 that we just released:
```
Airship.push.enableUserNotifications().then((status) => {})
```

You can now also query the current status using: `Airship.push.notificationStatus` and listen for changes using `Airship.push.onNotificationStatusChanged(listener)`
