### ISSUE TITLE
Android notifications are not displayed as Heads-up notifications

### ISSUE THREAD

**Issue by jschmitz1** [urbanairship/airship-flutter#181]
# Preliminary Info

### What Airship dependencies are you using?
airship_flutter 7.0.0

### What are the versions of any relevant development tools you are using?
macOS Venture 13.0.1,  XCode 14.3.1,  Flutter 3.10.5, Android 13

# Report

### What unexpected behavior are you seeing?
I am trying to get the notifications to be displayed as heads-up notifications on Android (https://developer.android.com/develop/ui/views/notifications#Heads-up).
I created a custom notification channel using the `ua_custom_notification_channels.xml` file in `android/app/src/main/res/xml`:

`<resources>
    <NotificationChannel
        id="<channelID>"
        name="customDefaultChannel"
        description="custom_channel_with_high_importance"
        importance="4" />
</resources>`

I am using the created notification channel during airship setup:

` Airship.takeOff(AirshipConfig(
    inProduction: true,
    productionEnvironment: ConfigEnvironment(
        appKey: store.state.staticJsonConfig!.airshipAppKey,
        appSecret: store.state.staticJsonConfig!.airshipAppSecret,
        logLevel: LogLevel.info),
     androidConfig: AndroidConfig(
      notificationConfig: AndroidNotificationConfig(
        defaultChannelId: "<channelID>"
      )
    ),
  ));`

However, when i send notifications, they are not displayed as heads-up notifications. I did not find any airship documentation about the "importance" attribute in the xml file but i tried the values 4 and 5 and it does not seem to make a difference.
I rarely send notifications (once a month) but when i do, i would prefer if they were displayed as a heads-up notification.

### What is the expected behavior?
The notification should be displayed as a heads-up notification on Android

### What are the steps to reproduce the unexpected behavior?
I outlined the steps above

**Comment by rlepinski** [comment]
Android really only wants you to create the channel once, after that its available to the end user to customize. Because of that, we only will create the channel once. 

Could you make sure its a new install or do a net new channel for testing? Then when you get the notification could you verify the channel by long pressing the notification and go to settings to see that it matches the rest of the details (description and name)?

**Comment by jschmitz1** [comment]
Thanks for the explainer, this works for us now
