### ISSUE TITLE
Calling Airship.push.iOS.resetBadge crashes the app

### ISSUE THREAD

**Issue by b-nugent** [urbanairship/airship-flutter#184]
# Preliminary Info

### What Airship dependencies are you using?
airship_flutter `v7.1.0`

### What are the versions of any relevant development tools you are using?
Flutter `v3.7.11`, Dart `v2.19.6`

# Report

### What unexpected behavior are you seeing?
When attempting to call `Airship.push.iOS.resetBadge` we are seeing that the app is crashing. The error logged before the crash is as follows:

```
Unsupported value: () of type __SwiftValue
*** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:338
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x191828cb4 0x18a8c43d0 0x18bfba54c 0x108229b10 0x1082263cc 0x102571600 0x102572850 0x102578aad 0x102577a39 0x102578575 0x19bbeadd9)
* thread #35, queue = 'com.apple.root.user-initiated-qos.cooperative', stop reason = signal SIGABRT
    frame #0: 0x00000001d07e5578 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`:
->  0x1d07e5578 <+8>:  b.lo   0x1d07e5598               ; <+40>
    0x1d07e557c <+12>: pacibsp 
    0x1d07e5580 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1d07e5584 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
```
Calling out to `Airship.push.iOS.setBadge(0)` works fine, so we have a mitigation strategy available, but I wanted to make sure attention was brought to this issue.

### What is the expected behavior?
Calling `Airship.push.iOS.resetBadge` does not result in a crash and will successfully reset the badge count.

### What are the steps to reproduce the unexpected behavior?
Calling `Airship.push.iOS.resetBadge` in any way

### Do you have logging for the issue?
Logging provided above

**Comment by Apekka** [comment]
A patch just got released, you can update to 7..1.1 to fix this crash , sorry about that !
