### ISSUE TITLE
AirshipChannelCreatedEvent not found

### ISSUE THREAD

**Issue by viniciusfragelli** [urbanairship/airship-flutter#2]
Good Evening, i'm trying to integrate Airship into a project to send push notifications. On the Android, works fine with the correct dependencies, but on iOS, when i do the 'pod install' and try to run the project, it says that it can't found the class 'AirshipChannelCreatedEvent'.

**Logs:**

Xcode's output:
↳
    === BUILD TARGET airship OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/viniciusfragellisenff/Documents/flutter/.pub-cache/git/airship-flutter-7ca75191af62a4c577df5ce064a8b6f4151825e7/ios/Classes/Events/AirshipChannelUpdatedEvent.swift:3:36: error: use of undeclared type 'AirshipChannelCreatedEvent'
    class AirshipChannelUpdatedEvent : AirshipChannelCreatedEvent {
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/viniciusfragellisenff/Documents/flutter/.pub-cache/git/airship-flutter-7ca75191af62a4c577df5ce064a8b6f4151825e7/ios/Classes/Events/AirshipChannelUpdatedEvent.swift:4:18: error: property does not override any property from its superclass
        override var eventType: AirshipEventType {
        ~~~~~~~~     ^
    /Users/viniciusfragellisenff/Documents/flutter/.pub-cache/git/airship-flutter-7ca75191af62a4c577df5ce064a8b6f4151825e7/ios/Classes/Events/AirshipChannelUpdatedEvent.swift:6:20: error: type 'AirshipEventType' has no member 'ChannelUpdated'
                return AirshipEventType.ChannelUpdated

**Pods that it install:**

Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `airship` from `.symlinks/plugins/airship/ios`
Downloading dependencies
Using Flutter (1.0.0)
Using UrbanAirship-iOS-AppExtensions (10.2.2)
Using UrbanAirship-iOS-SDK (10.2.2)
Using airship (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 3 dependencies from the Podfile and 4 total pods installed.

Best regards,

**Comment by rlepinski** [comment]
Thanks for the report. Ill see if I can resolve this today

**Comment by rlepinski** [comment]
Should be fixed in master. Please let me know if you run into any other issues.
