### ISSUE TITLE
Push registration failed - Android

### ISSUE THREAD

**Issue by rlee1990** [urbanairship/airship-flutter#204]
# Preliminary Info

### What Airship dependencies are you using?

```airship_flutter: ^7.4.0```

### What are the versions of any relevant development tools you are using?
I am using VSCode with Flutter Channel stable, 3.19.2

# Report

### What unexpected behavior are you seeing?
I am receiving the below error when the app is loaded. It shows the device in the dashboard but that it is opted out even though I added all the code to enable it and push notifications have been enabled.

```
UALib(23602): PushManager - Push registration failed with error: FCM error Default FirebaseApp is not initialized in this process com.socialjawn.supabase.test.supabase_social_jawn_test. Make sure to call FirebaseApp.initializeApp(Context) first.. Will retry.
```

### What is the expected behavior?
For the android device to be opted in and receive push notifications that are sent.

**Comment by rlepinski** [comment]
That error happens if firebase fails to initialize. Could you verify you have a google-services.json file located in the app directory for android and that your package name matches what is expected for the FCM project?

**Comment by rlee1990** [comment]
@rlepinski yes the google-services.json file is located in the app directory under Android. The package name is an exact match. I even did a test push from firebase and it came through.

**Comment by rlee1990** [comment]
@rlepinski here they are
[output-metadata.json](https://github.com/urbanairship/airship-flutter/files/15379103/output-metadata.json)

**Comment by rlepinski** [comment]
I need the AndroidManifest.xml file, might want to check it for secrets before posting it or you can email it to me at ryan.lepinski@airship.com

**Comment by rlee1990** [comment]
@rlepinski I just emailed it to you
