### ISSUE TITLE
setPaused and setDisplayInterval methods disappeared in version 7.8.0

### ISSUE THREAD

**Issue by cap-ylegarrec** [urbanairship/airship-flutter#216]
# Preliminary Info

### What Airship dependencies are you using?
7.8.0

### What are the versions of any relevant development tools you are using?
Not relevant the issue is visible in the source code of version 7.8.0
 
# Report

### What unexpected behavior are you seeing?
Airship.inApp.setPaused and Airship.inApp.setDisplayInterval methods disappeared in version 7.8.0 without mention in the release note and without updating the documentation. 

### What is the expected behavior?
Put those methods back or update the documentation with workaround.

### What are the steps to reproduce the unexpected behavior?
Just try to call the methods
 
### Do you have logging for the issue?
No

**Comment by rlepinski** [comment]
We will get a patch out ASAP

**Comment by Ulrico972** [comment]
Hello, we released a patch for this issue today. It's the version 7.8.1.
