### ISSUE TITLE
Deep link from push notification does not get handled when app is terminated (since 7.8.0)

### ISSUE THREAD

**Issue by mcs-nuuk** [urbanairship/airship-flutter#224]
Hi,

# Preliminary Info

### What Airship dependencies are you using?
airship_flutter: 7.8.0

# Report

### What unexpected behavior are you seeing?
When the app is terminated and a push notification is received, tapping on the notification does not handle the deep link in the payload. This issue does not occur if the app is in the foreground or background; the deep link is correctly handled in those cases. **The bug appears to have been introduced in airship_flutter version 7.8.0, as version 7.7.1 works as expected.**

### What is the expected behavior?
The app should launch and handle the deep link in the push notification payload as it does when the app is in the background or foreground.

### What are the steps to reproduce the unexpected behavior?
- Terminate the app completely (not running in the background).
- Send a push notification containing a deep link in the payload.
- Tap on the notification.

Could you please help me with this?

**Comment by crow** [comment]
Thanks for the report - looking into it

**Comment by crow** [comment]
@mcs-nuuk I'm able to run the Android and iOS example apps, terminate them, send myself a push with a deep link to `uairship://app_settings` (built-in deep link to app settings) and open the deep link without issue on both platforms on 7.8.0.  

Is the behavior you're seeing only on Android - or are you also seeing it on iOS? There were some changes to how we handle event streams on Android between 7.7.1 and 7.8.0, so I can look into that next.

**Comment by mcs-nuuk** [comment]
@crow Oh, sorry, I forgot to mention it. I only have the problem on iOS.

**Comment by crow** [comment]
@mcs-nuuk Found the issue and will get a patch out soon. Thanks for your patience.

**Comment by crow** [comment]
@mcs-nuuk Just released [a patch](https://github.com/urbanairship/airship-flutter/tree/8.0.1) that should resolve the unintended deep linking behavior you've been seeing - feel free to reach out or open this back up if you experience any further issues.
