### ISSUE TITLE
(AirshipFrameworkProxy.AirshipProxyError, erro 1.)

### ISSUE THREAD

**Issue by miguelpruivo** [urbanairship/airship-flutter#235]
Hi,

I'm receiving this:
```
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: PlatformException(AIRSHIP_ERROR, Não foi possível concluir a operação. (AirshipFrameworkProxy.AirshipProxyError, erro 1.), Method: contact#identify, null)
flutter: 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
<asynchronous suspension>
#2      AirshipContact.identify (package:airship_flutter/src/airship_contact.dart:37:12)
<asynchronous suspension>
flutter: ----------------------------------------------------
```

when using this:
```
 Airship.contact.identify(md5.convert(utf8.encode(username)).toString());
 ```
Any tips? Thanks!

**Comment by crow** [comment]
@miguelpruivo Looks like this call should be fine. Are there Portuguese characters in the username? Are we sure the encode step isn't throwing an unchecked format exception for some usernames with special characters?

**Comment by miguelpruivo** [comment]
> @miguelpruivo Looks like this call should be fine. Are there Portuguese characters in the username? Are we sure the encode step isn't throwing an unchecked format exception for some usernames with special characters?

No, I already printed the string being identified with a breakpoint, its basically a normal hash.

**Comment by miguelpruivo** [comment]
Closing, it was an issue on our end.
