### ISSUE TITLE
Trouble with airship

### ISSUE THREAD

**Issue by miguelpruivo** [urbanairship/airship-flutter#240]
Hi,

I'm not sure what else I am missing, but I'm really having trouble in getting this to work. I already have the takeOff properly set, as well as my setup project (I actually have a live one as well) but we need to test in the TEST project some features.

I have a couple of users with the QA version of the product which try to do the 6x times channel id thing and it never shows up anything (being both on Android and iOS). Sometimes, I get an `ua:` but that's it. I suppose something must be missing but I don't know what.

Bundle id, team id, etc. is all fine (matching the project). 

Notifications are enabled as well and `Airship.push.notificationStatus.then((res) => res.areNotificationsAllowed);` returns `true`. 

So at this point I'm out of ideas. It's probably something simple, but I don't know what. Again, I can only use the TEST project.

Seeking for some advice.
Thanks.

**Comment by crow** [comment]
Have you carefully reviewed the [getting started documentation](https://docs.airship.com/platform/mobile/setup/sdk/flutter/)? If you haven't read through the documentation, please do so.

If you are looking for general assistance with your implementation and would like to do so in a private channel please contact support@airship.com

If you think there's a bug or issue with the plugin (or any other Airship dependency you're using) let's try to identify a specific issue you're having and start the process of troubleshooting it.

1. What Airship dependencies are you using and what are their versions? 
2. What unexpected behavior are you seeing?
3. What is the behavior you're expecting?
4. Can you outline the steps you take (and relevant code) to produce the unexpected behavior?

Please share as much of your relevant Airship implementation code as you feel comfortable with and please ensure any sensitive info is redacted. Any additional context you can provide can help speed up the process of troubleshooting significantly.

**Comment by miguelpruivo** [comment]
Hi, yes, I've been through that guide/documentation multiple times and everything is properly set in my app. 

The clue that should help is that with the 6 times closing/opening the app, I receive a `ua:` in the clipboard without any ID. Based on your implementation, it should help to identify what typically causes this (what config am I missing so it doesn't provide any ID?)

I also have FCM set in my app, not sure if it conflicts with airship somehow, but FCM alone is working fine, let me know.

Best,
Miguel

**Comment by crow** [comment]
What you're describing indicates you don't yet have a channel ID. Are you connected to the correct site? There are two sites and EU site and a US site:

  var config = AirshipConfig(
      defaultEnvironment: ConfigEnvironment(
          appKey: "REPLACE_WITH_YOUR_APP_KEY",
          appSecret: "REPLACE_WITH_YOUR_APP_SECRET"
      ),
      site: Site.eu, // use eu for EU cloud projects
      urlAllowList: ["*"],
      androidConfig: AndroidConfig(
          notificationConfig: AndroidNotificationConfig(
              icon: "ic_notification",
              accentColor: "#00ff00"
          )
      )
  );

  Airship.takeOff(config);

If the correct site is already set. Please enable debug logging and send over your logs on initialization with any sensitive info redacted.

**Comment by miguelpruivo** [comment]
This is how I am doing it:
```
    Airship.takeOff(AirshipConfig(
      inProduction: false,
      defaultEnvironment: ConfigEnvironment(
        logLevel: LogLevel.debug,
        appKey: switch (flavor) {
          Flavor.prod => Keys.airshipKeyPROD,
          Flavor.qa => Keys.airshipKeyQA,
          _ => Keys.airshipKeyQA
        },
        appSecret: switch (flavor) {
          Flavor.prod => Keys.airshipSecretPROD,
          Flavor.qa => Keys.airshipSecretQA,
          _ => Keys.airshipSecretQA
        },
      ),
      site: Site.eu,
    ));
    ```

I don't see any logs and it apparently initializes (or goes through this instruction) without any issues. No logs are printed.

**Comment by crow** [comment]
Focusing on iOS for troubleshooting:
Check:
- Bundle ID used in your app matches what's configured in go.airship.com
- App is properly provisioned and a provisioning profile or auth key is uploaded to go.airship.com

Try setting logging to verbose and launch your app - ensuring takeOff is called.

Send verbose logging to david.crow@airship.com. Don't post it here.

**Comment by crow** [comment]
Closing this for now as I haven't received any logging or a reply. Feel free to reopen this if you are still having trouble getting your channel id.
