### ISSUE TITLE
Messages in the message center on iOS appear as read first

### ISSUE THREAD

**Issue by wwwdata** [urbanairship/airship-flutter#26]
# Preliminary Info

### What Airship dependencies are you using?
1.0.1

### What are the versions of any relevant development tools you are using?
not relevant

# Report

### What unexpected behavior are you seeing?
When using the message center (basically just copy&pasting the example code), then it all works fine in Android. I see new messages as unread, after reading them in the detail view, they get marked as read. However on iOS, the initial state is read, and after reading them, they are marked as unread. I guess there is a simple small bug in the library.

### What is the expected behavior?
Messages are always unread when they are "new"

### What are the steps to reproduce the unexpected behavior?
Send a message and then open the notification center.

**Comment by crow** [comment]
@wwwdata I think I see where the issue is. I'll get a fix in and ensure it's in the upcoming release. Thank you very much for reporting this.

**Comment by crow** [comment]
@wwwdata the newest Airship flutter plugin ([airship_flutter](https://pub.dev/packages/airship_flutter)) is released and includes the fix.

Thanks again for reporting the issue.
