### ISSUE TITLE
Push Notification don't open activity after click

### ISSUE THREAD

**Issue by rlechetaudemy** [urbanairship/airship-flutter#55]
Hi,

I'm sending push notification through the console and the message arrives successfully on Android (i'm testing just android now).

To test it, I touch the Android Home button, to let the app go to the background.

But when I click in the notification, it don't open my app, it just close the notification.

I can see in the console that the message arrives in the Airship.onPushReceived event and when I click in the notification it arrives in the Airship.onNotificationResponse event.

This is the logs when my app receives the push.
[logs1.txt](https://github.com/urbanairship/airship-flutter/files/4783514/logs1.txt)

This is the logs after click in the notication:
[logs2.txt](https://github.com/urbanairship/airship-flutter/files/4783522/logs2.txt)

Can you help? Thank you.

**Comment by BrianBatchelder** [comment]
@rlechetaudemy : We apologize for not responding in a more timely manner. Are you still experiencing the issue?
