### ISSUE TITLE
Add Flutter Module to a Native App

### ISSUE THREAD

**Issue by rlecheta** [urbanairship/airship-flutter#56]
Hi, I'm doing this for a app, so I can migrate few modules of my app using flutter.
https://flutter.dev/docs/development/add-to-app

But the airship-flutter plugin doesn't work as a module because it was done with the old flutter plugin system and it should be migrated:
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

This is the error, after create a Flutter Module with the airship-flutter plugin:

`The plugin `airship_flutter` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.`

I think this is a easy fix, looking forward to see it, thank you.

**Comment by rlepinski** [comment]
Thanks for reporting this, we will update it in our next release.
