### ISSUE TITLE
Android not getting pushes- Ios does.

### ISSUE THREAD

**Issue by cookseym** [urbanairship/airship-flutter#60]
# Preliminary Info
iOS channels registered successfully, and using the airship test push and send to specific device works.
Android channels are registered successfully, but device does not receive pushes.  
Using RAW FCM and google APIs, device is able to receive push.
Airship console reports 0 pushes sent.

### What Airship dependencies are you using?
airship_flutter: ^3.0.2

# Report

### What unexpected behavior are you seeing?
Pushes from airship console never reach intended audience- no logs.

### What is the expected behavior?
Push received and shown in notification bar

### What are the steps to reproduce the unexpected behavior?
1. Configure a airship project with flutter sdk 3.0.2
2. Register FCM from google firebase in airship project android channel
3. Install app, push to newly configured channel id

### Do you have logging for the issue?
No logs are outputted that show any adverse issues.

**Comment by marc-scig** [comment]
Hi @cookseym,

Thanks for letting us know. Despite the fact that there are no obvious issues shown in the logs, it would still be helpful to provide logs around takeOff and push registration since it will help us to trace what the SDK is doing. I can try to reproduce the issue tomorrow, but in the meanwhile the most helpful info would be those logs as well as the way you're configuring/enabling push in your code.

**Comment by cookseym** [comment]
@marc-scig  I am following the instructions from the readme- and the sample app.

I have double checked that the app has push permissions and followed the troubleshooting guide here - https://support.airship.com/hc/en-us/articles/213492643-GCM-FCM-Troubleshooting-Guide

Here is the log:
```
Airship taking off!
Airship log level: 3
Airship ready!
14941-15000 D: Autopilot - Airship ready!
onAirshipReady
14941-15046 I: Inbox updated link
14941-15046 I:         "airship_channel_id": "b7c34f5c-c95a-4eda-8e9a-ba789d80ca1c
14941-15011 D: EventApiClient - Sending analytics events. Request: com.urbanairship.http.Request@e45c581 Events: [{"event_id":"7f088637-5807-4b08-91b8-c3625b63bf8d","time":"1596216743.776","data":{"session_id":"7d68adcf-4896-4b73-8312-51d880e42379","connection_type":"wifi","connection_subtype":""},"type":"app_background"}, {"event_id":"62116c3f-5e74-461e-a814-3ce7cdda1f22","time":"1596216750.994","data":{"daylight_savings":true,"carrier":"Android","package_version":"0.9.1","connection_type":"wifi","connection_subtype":"","os_version":"10","session_id":"759d98ad-3d25-401c-80e0-ecb7dc4d6250","time_zone":-18000,"lib_version":"13.1.0"},"type":"app_foreground"}]

**Comment by BrianBatchelder** [comment]
@cookseym : Are you calling`Airship.setUserNotificationsEnabled(true);`? Without that, Airship will still become ready and get a channel. The push will be received, which you can see using `Airship.onPushReceived.listen()`, but the push will not display.

**Comment by BrianBatchelder** [comment]
Look up your channel in the [airship dashboard](https://go.airship.com). Look in your project, under "Audience" -> "Contact Lookup". Ensure that it is opted-in. If it is, please enable verbose logging in your app and send us the log.

**Comment by cookseym** [comment]
@BrianBatchelder  Thanks for the suggestions-  
I am setting ```Airship.setUserNotificationsEnabled(true)```

After debugging this- I see that anytime the firebase messaging dependency (current version is ^6.0.16) is included in the flutter project- pushes do not come to airship.  There are several issues I see.

1)  I am trying to get the FCM push id.  I see in the callback for getting the channel id, there is event.registrationToken which gives me what I want- however, this callback doesn't happen if the channel is already created.  Is there a way in your SDK to get the FCM reg id consistently?  
2) If the dependency `firebase-messaging` is included in the project- the airship push never comes through.  This is what was happening- we use another SDK which accesses firebase-messaging.

**Comment by rlepinski** [comment]
@cookseym My guess is that the other firebase dependency is registering a firebase service that is higher priority than ours. Unfortunately only 1 service is able to receive a messages for an app. See https://docs.airship.com/platform/android/getting-started/#extending-the-firebasemessagingservice

You could modify ours in the manifest to be higher priority but that would prevent the other dependency from working fully. You will either have to drop one of the plugins, make airship higher priority (breaking the other one), or write native code to forward messages to both. For the token we can add a new method in a future release.
