### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by andrewescutia** [urbanairship/airship-flutter#78]
Hi, can we get a Null Safety version of this flutter package? I can take a stab at an initial PR. let me know. Thanks!

**Comment by rlepinski** [comment]
Yep, added to our backlog. If you want to do the initial PR you just have to sign our [contribution agreement ](https://docs.google.com/forms/d/e/1FAIpQLScErfiz-fXSPpVZ9r8Di2Tr2xDFxt5MgzUel0__9vqUgvko7Q/viewform). 

Do you know if this will force the min version of Flutter to 2.0?

**Comment by andrewescutia** [comment]
it will not. null safe packages are compatible with < 2.0

**Comment by rlepinski** [comment]
Released in 4.3
