### ISSUE TITLE
Add the ability to send a RegionEvent

### ISSUE THREAD

**Issue by andrewescutia** [urbanairship/airship-flutter#81]
The current Flutter SDK allows for the ability to add a CustomEvent but I need the ability to add a RegionEvent (exists in android and ios SDKs) in order to complete a Gimbal Integration. In looking through the implementation it doesnt appear that this can be achieved through the CustomEvent implementation and would require the additional type.

**Comment by rlepinski** [comment]
Does Gimbal have a flutter plugin or are you building that as well? In the past we provided a module directly for our gimbal adapter instead of exposing region events to the framework.

https://github.com/urbanairship/react-native-gimbal-adapter

**Comment by andrewescutia** [comment]
I was building the gimbal plugin internally. This is coming from a Xamarin port where it looks like RegionEvent and the Builder for it were exposed but I do see you manage various other Gimbal Adapters. Is there a plan for a Flutter one? This currently isn't a high urgency issue on our end as the port has a ways to go.

________________________________

**Comment by rlepinski** [comment]
We don't have any plans yet, but I can add it to our backlog. Do you need the gimbal events in the flutter context or just a handle to enable/disable?

Trying to route events through flutter might be problematic. I am pretty sure will have to deal with a background isolate https://flutter.dev/docs/development/packages-and-plugins/background-processes. It might be easier to use the GimbalAdapters directly in your project and just expose an enable flag through flutter to kickoff gimbal.
https://github.com/urbanairship/android-gimbal-adapter
https://github.com/urbanairship/ios-gimbal-adapter

**Comment by andrewescutia** [comment]
My original plan was to create a Flutter plugin for Gimbal which would return an EventChannel stream for onVisit and onVisitEnd events. Then in Flutter make the Airship call when those events are received. 

Looking at the adapters you posted though I think it would be easier to just create a Flutter plugin for those Adapters themselves with start/stop capabilities from Flutter. Should be straight forward enough. If you ever create Flutter plugins for those adapters I can always swap them out. Thanks!
