### ISSUE TITLE
Release null-safe version on pub.dev

### ISSUE THREAD

**Issue by vincevargadev** [urbanairship/airship-flutter#83]
I see that since #80, the package is null safe.

Would you like to publish the new version on pub.dev? Currently, if I want to use the null-safe version, I'd need to use the package as a [`git` dependency](https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages).

**Comment by rlepinski** [comment]
We will get an update out soon. We have someone working isolate support for background pushes that I was hoping to get in, but if that is not ready by next week we will publish an update.

**Comment by rlepinski** [comment]
Released!
