### ISSUE TITLE
Unable to listen to events push notification events when app is not launched

### ISSUE THREAD

**Issue by danallen88** [urbanairship/airship-flutter#86]
# Preliminary Info

### What Airship dependencies are you using?
Flutter SDK 4.2.0

### What are the versions of any relevant development tools you are using?
```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.3.1 20E241 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
[✓] Connected device (2 available)
```

# Report

### What unexpected behavior are you seeing?
An app that is not launched cannot react to push notifications with the Airship SDK.  For example, configuring a listener at the app level such as `Airship.onNotificationResponse.listen((event) => ...);` which extracts some data from the push payload, and navigates to a route with that data, does not allow the user to navigate to that route when the app is not launched.  If the app is foregrounded or backgrounded, it works as expected.  There are no listeners for the Airship SDK for dealing with a not launched scenario like Firebase has for their Cloud Messaging.

### What is the expected behavior?
A not launched app is able to navigate to a specific route after configuring the Airship listener.  Minimally, there should be another listener available in the SDK that covers this scenario.

**Comment by rlepinski** [comment]
Thanks for the report and sorry for the delay in response. I'll have someone take a look at this immediately.

**Comment by oristanovic** [comment]
@danallen88 How early in the app lifecycle do you call `Airship.onNotificationResponse.listen((event) => ...);`
Could you try adding the listener earlier (for instance in `initState`) and checking if you receive the open notification response event?

**Comment by danallen88** [comment]
@oristanovic Our app structure looks like this:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get_it/get_it.dart';
import 'package:our_app/core/dependency_injection/composition_root.dart';
import 'package:our_app/core/dependency_injection/injector.dart';
import 'package:our_app/root_provider.dart';

GetIt getIt = GetIt.instance;
void main({@required CompositionRoot compositionRoot}) {
  final GlobalKey<NavigatorState> navigatorKey =
      new GlobalKey<NavigatorState>();

  compositionRoot.setNavigatorKey(navigatorKey);

  var injector = Injector(
    child: RootProvider(
      navigatorKey: navigatorKey,
    ),
    compositionRoot: compositionRoot,
  );

  WidgetsFlutterBinding.ensureInitialized();

  _runApp(injector);
}

void _runApp(Injector injector) {
  runApp(injector);
}
```

where `RootProvider` is a widget that initializes some themes, and has as a child the `MyApp` widget.  In the `initState` hook for `MyApp` is where we initialize this listener.  Practically speaking, I can't imagine it makes sense to push it any further up the stack.  `MyApp` is the widget that hosts the `MaterialApp` widget, so it's about as high up as I would imagine it needs to be.

**Comment by Ulrico972** [comment]
Indeed, there is no need to initialize the listener any further up in the stack. The ```initState``` is fine.
I tried to reproduce the behavior on a sample app but it seems to work well.
Could you try to simplify a bit your code to directly use ```runApp``` with your ```MyApp``` widget in order to see if the use of your injector maybe creates a delay before initializing the listener ?

**Comment by danallen88** [comment]
@Ulrico972 I'm not sure what the path forward is here - I can't get around the fact that I need an injector, so even if it did work on a basic app, that doesn't fit our use case.  I set up the listener before runApp gets called, and it has the same behavior.  What is the requirement from the Airship side - that it runs in initState in the widget that hosts the MaterialApp widget?  Does it have to be run before something else runs?  I don't quite understand why it would work on a sample app only if there was no "delay".  Why is it time dependent?

**Comment by rlepinski** [comment]
@danallen88 What platform are you testing on? iOS or Android?

**Comment by danallen88** [comment]
@rlepinski This is on iOS.  We're developing for both platforms, but so far I've been testing these changes on iOS only.

**Comment by Ulrico972** [comment]
@danallen88 Sorry, I was testing on Android.
I made the test on iOS and it seems to work fine too. Although, it's more difficult to test it on iOS since we cannot debug or log anything when the app is killed.
So I used an alert dialog to check if the event was happening and when I clicked on the push notification, the app opens and the popup showed up well.
![Capture d’écran 2021-06-17 à 09 53 21](https://user-images.githubusercontent.com/24393953/122410417-306cc700-cf84-11eb-8e55-ea108d24d8e0.png)

Then I was wondering how did you test it on your side ? Maybe that could help me understand how to reproduce your behavior.
Also, could you maybe try to show a popup to see what's happening on the listening ?

**Comment by danallen88** [comment]
Hi @Ulrico972 - I managed to instrument my app to produce an alert dialog with the push payload when I receive pushes.  I'm in the same position as before - the dialog is populated with the payload when the app is launched from a notification if the app was already foregrounded or backgrounded, but if the app is terminated, the payload is empty.  Intuitively this makes sense - there's no listener setup because the app isn't running, so there's some default action of the SDK to take me to a default screen when no listener is handling the notification.

This leads me to ask what is exactly required by the Airship SDK in order to have a listener registered that somehow persists after the app has been terminated?  It has to be an issue with my implementation, but as best I can tell I have followed the Flutter Airship SDK documentation as closely as possible.  I am curious what the technical mechanism is that exists in the SDK that allows a listener to persist even after app termination.  That might guide us to where the issue in my implementation lies.

**Comment by rlepinski** [comment]
@danallen88 The plugin stores any events that happen before a listener is added for that event name, then once a listener is added it dispatches the pending events. Do you have another listener somewhere in your code?

**Comment by danallen88** [comment]
@rlepinski I do not - this listener is the one and only listener we have configured for Airship.  I will also note the behavior is the same on Android so I know it's not a platform difference (and therefore even more likely an implementation issue).

**Comment by danallen88** [comment]
I really can't - the app is so complex that doing so would be a significant effort.  I understand how vital this is to troubleshooting the issue.  We are a paying customer, is there any channel through which we can receive technical support on the implementation on the app itself?  I've opened tickets with support but they only added a feature request for this.

**Comment by rlepinski** [comment]
Could you contact me directly at ryan.lepinski@airship.com ? We can set something up

**Comment by danallen88** [comment]
Will do.  Thank you all for your attentive support.  Feel free to close this issue as it is shaping up to be an implementation issue and not an issue with the plugin.
