### ISSUE TITLE
can't run successful in android platform after add airship_flutter plugin

### ISSUE THREAD

**Issue by huhuan-yj** [urbanairship/airship-flutter#87]
# Preliminary Info

### What Airship dependencies are you using?

airship_flutter: ^4.3.0
### What are the versions of any relevant development tools you are using?

>[✓] Flutter (Channel stable, 2.2.0, on macOS 11.4 20F71 darwin-x64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[✓] VS Code (version 1.57.0)
[✓] Connected device (3 available)
# Report

### What unexpected behavior are you seeing?

We add airship plugin follow the guide doc both ios and android. But can't run successful in android device. It cause BuildConfig not found we used in other Class.When remove airship_flutter it can run successful without any other single code!
### What is the expected behavior?

Run successful both on ios and android platform.
### What are the steps to reproduce the unexpected behavior?

Just add airship plugin follow the guide doc [flutter getting started](https://docs.airship.com/platform/flutter/getting-started/)
### Do you have logging for the issue?

error message "Unresolved reference: BuildConfig" used in Logger.setLoggable(BuildConfig.DEBUG)

**Comment by huhuan-yj** [comment]
When i downgrade to version 4.2.0, it can run successful .But without null safety is not I want

**Comment by rlepinski** [comment]
What version of gradle is your project using?

**Comment by huhuan-yj** [comment]
> What version of gradle is your project using?

gradle version is 6.8-rc-3

**Comment by huhuan-yj** [comment]
I create a new project and add airship_flutter, it works. Then I compare the difference, I changed gradle version from 6.8-rc-3 to 6.7, it still not works, after that, I changed kotlin version from 1.37.0 to 1.35.0,It works. But I don't know why. In my project I add multi plugins, those plugins never face the problem

**Comment by rlepinski** [comment]
@huhuan-yj looks like our plugin is using kotlin 1.4.21, could you try that version?
