### ISSUE TITLE
Fatal error: TakeOff must be called before accessing Airship

### ISSUE THREAD

**Issue by mauro-xonne** [urbanairship/airship-flutter#99]
# Preliminary Info

### What Airship dependencies are you using?
airship_flutter: ^5.0.1

### What are the versions of any relevant development tools you are using?
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (4 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

Xcode Version 13.1 (13A1030d)

# Report

### What unexpected behavior are you seeing?
Compiling Flutter project using latest Xcode and latest airship_flutter dependency, generates a fatal error during app launch.

### What is the expected behavior?
App should start

### What are the steps to reproduce the unexpected behavior?
Update airship_flutter and build project with the most recent Xcode

### Do you have logging for the issue?
`2021-11-12 14:50:06.092063+0100 Runner[1027:180872] Could not load the “LaunchImage” image referenced from a nib in the bundle with identifier “com.chiesi.bt4uenterprise”
AirshipKit/Airship.swift:128: Fatal error: TakeOff must be called before accessing Airship.
2021-11-12 14:50:06.112434+0100 Runner[1027:180872] AirshipKit/Airship.swift:128: Fatal error: TakeOff must be called before accessing Airship.`

**Comment by rlepinski** [comment]
Looks like a change was made where you have to manually call takeOff in the app delegate. We are working on a release to fix this. Should be out this week or early next week.

**Comment by rlepinski** [comment]
Should be fixed in 5.1.0
